# Generated by Django 4.2.7 on 2023-11-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertise',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
