# Generated by Django 4.2.7 on 2023-11-20 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import legal_services.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('legal_services', '0002_alter_expertise_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='legal_services.expertise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QueryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to=legal_services.models.create_path_image)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='legal_services.query')),
            ],
        ),
    ]
