# Generated by Django 4.2.7 on 2023-11-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_services', '0003_query_queryfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='contacted_before',
            field=models.CharField(default='No', max_length=5),
        ),
    ]
