# Generated by Django 4.2.7 on 2023-11-25 09:18

from django.db import migrations, models
import legal_services.models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_services', '0004_query_contacted_before'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=legal_services.models.create_path_image),
        ),
    ]
