# Generated by Django 4.2.7 on 2023-11-10 16:36

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(null=True, upload_to=authentication.models.create_path_image)),
                ('father_name', models.CharField(blank=True, default='', max_length=255)),
                ('spouse_name', models.CharField(blank=True, default='', max_length=255)),
                ('date_of_birth', models.DateField(auto_now_add=True)),
                ('caste', models.CharField(blank=True, default='', max_length=20)),
                ('religion', models.CharField(blank=True, default='', max_length=20)),
                ('phone', models.CharField(blank=True, default='', max_length=10)),
                ('aadhar', models.CharField(blank=True, default='', max_length=12)),
                ('age', models.PositiveSmallIntegerField(blank=True, default=18)),
                ('gender', models.CharField(blank=True, default='Male', max_length=10)),
                ('occupation', models.CharField(blank=True, default='', max_length=255)),
                ('employ_details', models.CharField(blank=True, default='', max_length=255)),
                ('salary', models.CharField(default='0', max_length=10)),
                ('district', models.CharField(blank=True, default='', max_length=50)),
                ('taluka', models.CharField(blank=True, default='', max_length=50)),
                ('user_type', models.CharField(default='COMMON', max_length=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
